-- Tabela de Unidades
CREATE TABLE units (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  city TEXT NOT NULL,
  state TEXT NOT NULL,
  address TEXT NOT NULL,
  phone TEXT NOT NULL,
  manager TEXT NOT NULL
);

-- Tabela de Usuários
CREATE TABLE users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  email TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL,
  role TEXT NOT NULL,
  unit_id BIGINT REFERENCES units(id)
);

-- Tabela de Alunos
CREATE TABLE students (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  belt TEXT NOT NULL,
  age INTEGER NOT NULL,
  registration_date DATE NOT NULL,
  last_attendance DATE,
  unit_id BIGINT REFERENCES units(id),
  phone TEXT NOT NULL,
  contract_active BOOLEAN DEFAULT FALSE,
  contract_end_date DATE
);

-- Tabela de Presenças
CREATE TABLE attendance (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  student_id BIGINT REFERENCES students(id),
  date DATE NOT NULL,
  present BOOLEAN DEFAULT TRUE,
  unit_id BIGINT REFERENCES units(id)
);