const admin = require('firebase-admin');
const axios = require('axios');
const fs = require('fs');
const path = require('path');

// Load environment variables from functions/.env file if it exists
const envPath = path.join(__dirname, '..', 'functions', '.env');
if (fs.existsSync(envPath)) {
  const lines = fs.readFileSync(envPath, 'utf8').split('\n');
  for (const line of lines) {
    const match = line.match(/^\s*([\w.-]+)\s*=\s*(.*)?\s*$/);
    if (match) {
      const key = match[1];
      let val = match[2] || '';
      if (val.startsWith('"') && val.endsWith('"')) {
        val = val.substring(1, val.length - 1);
      } else if (val.startsWith("'") && val.endsWith("'")) {
        val = val.substring(1, val.length - 1);
      }
      process.env[key] = val;
    }
  }
}

// Initialize Firebase Admin
const serviceAccount = require('../intranet-kihap-firebase-adminsdk-fbsvc-43327c2f72.json');
admin.initializeApp({
  credential: admin.credential.cert(serviceAccount)
});
const db = admin.firestore();

// Default MP Access Token
const defaultAccessToken = process.env.MERCADOPAGO_ACCESS_TOKEN;
if (!defaultAccessToken) {
  console.warn('Warning: MERCADOPAGO_ACCESS_TOKEN environment variable is not defined.');
}

async function main() {
  console.log('Fetching active/authorized tuition subscriptions from Firestore...');
  const snapshot = await db.collection('evo_students')
    .where('tuitionStatus', 'in', ['active', 'authorized'])
    .get();

  console.log(`Found ${snapshot.size} students with active tuitionStatus.`);

  for (const doc of snapshot.docs) {
    const student = doc.data();
    const preapprovalId = student.mpPreapprovalId;
    if (!preapprovalId) {
      console.log(`Student ${student.firstName} ${student.lastName} has no mpPreapprovalId.`);
      continue;
    }

    console.log(`\n--------------------------------------------`);
    console.log(`Student: ${student.firstName} ${student.lastName} (${student.idMember})`);
    console.log(`Plan ID: ${student.tuitionPlanId}`);
    console.log(`Preapproval ID: ${preapprovalId}`);
    console.log(`Unit ID: ${student.unitId}`);

    // Resolve MP Token for the unit
    let customToken = null;
    if (student.unitId) {
      const mpAccSnap = await db.collection('mercadopagoAccounts').doc(student.unitId).get();
      if (mpAccSnap.exists) {
        customToken = mpAccSnap.data().accessToken;
        console.log(`Using custom token for unit ${student.unitId}`);
      }
    }
    const token = customToken || defaultAccessToken;

    try {
      // 1. Get Preapproval details
      const preapprovalRes = await axios.get(`https://api.mercadopago.com/preapproval/${preapprovalId}`, {
        headers: { Authorization: `Bearer ${token}` }
      });
      const preapproval = preapprovalRes.data;
      console.log(`MP Status: ${preapproval.status}`);
      console.log(`Payer Email: ${preapproval.payer_email}`);
      console.log(`Reason: ${preapproval.reason}`);
      console.log(`Next Payment Date: ${preapproval.next_payment_date}`);
      console.log(`Summarized:`, preapproval.summarized);
      console.log(`Last modified: ${preapproval.last_modified}`);

      // 2. Search authorized payments (invoices)
      const paymentsRes = await axios.get(`https://api.mercadopago.com/v1/authorized_payments/search?preapproval_id=${preapprovalId}`, {
        headers: { Authorization: `Bearer ${token}` }
      });
      const payments = paymentsRes.data.results || [];
      console.log(`Total payments generated by MP: ${payments.length}`);
      payments.forEach((p, i) => {
        console.log(`  [Payment ${i+1}] ID: ${p.id}, Status: ${p.status}, Date: ${p.payment?.date_created || p.last_modified}, Amount: ${p.transaction_amount}, Payment ID: ${p.payment?.id || 'N/A'}`);
      });

    } catch (err) {
      console.error(`Error querying Mercado Pago for preapproval ${preapprovalId}:`, err.response?.data || err.message);
    }
  }
}

main().then(() => process.exit(0)).catch(err => {
  console.error(err);
  process.exit(1);
});
